delete from MPA;
delete from USERS;
delete from FILMS;
delete from GENRE;
delete from FILM_GENRE;

INSERT INTO MPA (MPA) VALUES ('G');
INSERT INTO MPA (MPA) VALUES ('PG');
INSERT INTO MPA (MPA) VALUES ('PG-13');
INSERT INTO MPA (MPA) VALUES ('R');
INSERT INTO MPA (MPA) VALUES ('NC-17');

INSERT INTO GENRE (GENRE) VALUES ('Комедия');
INSERT INTO GENRE (GENRE) VALUES ('Драма');
INSERT INTO GENRE (GENRE) VALUES ('Мультфильм');
INSERT INTO GENRE (GENRE) VALUES ('Триллер');
INSERT INTO GENRE (GENRE) VALUES ('Документальный');
INSERT INTO GENRE (GENRE) VALUES ('Боевик');